version: '3.9'

services:

  postgres_db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_DB: ${POSTGRE_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
  nestjs_app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports: 
      - "4000:${PORT}"
    depends_on:
      - postgres_db
    volumes:
      - ./:/var/lib/postgresql
